# Generated by Django 5.0.3 on 2024-03-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_qrcodedata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('qr_code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
