# Generated by Django 5.0.3 on 2024-03-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_qrcodescan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scanned_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
