# Generated by Django 5.0.3 on 2024-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_scanned_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_points', models.IntegerField()),
            ],
        ),
    ]
