# Generated by Django 5.0.3 on 2024-03-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_giftpoint_profilepoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftPoint',
        ),
    ]
