# Generated by Django 5.0.3 on 2024-03-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_giftpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePoint',
        ),
    ]
