# Generated by Django 4.1.2 on 2024-03-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_qrcodedata_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpoint',
            name='qr_code_image',
            field=models.ImageField(default='gifts/default.png', upload_to='gifts/'),
        ),
    ]
