# Generated by Django 4.1.2 on 2024-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_giftpoint_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpoint',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
