# Generated by Django 4.1.2 on 2024-03-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_giftpoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gifts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.giftpoint'),
        ),
    ]
