# Generated by Django 4.1.2 on 2024-03-18 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_profile_gifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gifts',
        ),
        migrations.CreateModel(
            name='UserGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.giftpoint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
