# Generated by Django 4.1.2 on 2024-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_profile_gifts_usergifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergifts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
